from time import sleep 

sleep(4)
print("ATENCION SIGA LA GUIA INFORMATIVA")
sleep(5)
print("MINER SCRIPT ESTA SIENDO EJECUTADO...")
sleep(3)
print("MINER SCRIPT FUE ECHO POR GD")
sleep(2)
print("\nSi continua hacepta seguir con el seting:")
res = input("Escriba >ACEPTO< : ")
sleep(3)
print("\nIniciando...")
sleep(10)
print("10%")
sleep(11)
print("30%")
sleep(13)
print("58%")
sleep(5)
print("72%")
sleep(9)
print("99%")
sleep(20)
print("\nFelicidades el proceso no ha tenido ningun error!!!")
print("Ahora siga las indicaciones de la guia.")
